name: home_manager
description: A new Flutter application.

version: 2.4+33

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fluttertoast:
  states_rebuilder: 2.3.1
  flutter_launcher_icons:
  line_icons:
  url_launcher:
  cloud_firestore:
  firebase_auth:
  google_sign_in:
  share:
  upi_india:
  bubble_bottom_bar:
  intl_phone_number_input:
  sms_autofill:
  toggle_switch:
  firebase_core:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/